chore: update pipeline (#39)

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -8,111 +8,72 @@ trigger: none
 
 variables:
   - group: "Github and NPM secrets"
-  - group: InfoSec-SecurityResults
   - name: tags
     value: production,externalfacing
 
-jobs:
-  # These steps have to run on a windows machine,
-  # and therefore unfortunately can't be integrated in the regular steps
-  - job: Compliance
-    displayName: Compliance checks
-    pool: uifabric-windows-2019-small
-    workspace:
-      clean: all
-    steps:
-      - task: UseDotNet@2
-        condition: succeededOrFailed()
-        displayName: "Use .NET Core sdk 3.x"
-        inputs:
-          version: 3.x
-          steps:
+resources:
+  repositories:
+    - repository: 1esPipelines
+      type: git
+      name: 1ESPipelineTemplates/1ESPipelineTemplates
+      ref: refs/tags/release
 
-      - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@3
-        condition: succeededOrFailed()
-        displayName: "🧭 Run Credential Scanner"
-        inputs:
-          debugMode: false
+extends:
+  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
+  parameters:
+    pool:
+      name: Azure-Pipelines-1ESPT-ExDShared
+      image: windows-latest
+      os: windows # We need windows because compliance task only run on windows.
+    stages:
+      - stage: main
+        jobs:
+          - job: Release
+            pool:
+              name: "1ES-Host-Ubuntu"
+              image: "1ES-PT-Ubuntu-20.04"
+              os: linux
+            workspace:
+              clean: all
+            steps:
+              # For multiline scripts, we want the whole task to fail if any line of the script fails.
+              # ADO doesn't have bash configured this way by default. To fix we override the SHELLOPTS built-in variable.
+              # https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
+              # The options below include ADO defaults (braceexpand:hashall:interactive-comments) plus
+              # errexit:errtrace for better error behavior.
+              - script: |
+                  echo "##vso[task.setvariable variable=shellopts]braceexpand:hashall:interactive-comments:errexit:errtrace"
+                displayName: Force exit on error (bash)
 
-      - task: securedevelopmentteam.vss-secure-development-tools.build-task-eslint.ESLint@1
-        condition: succeededOrFailed()
-        displayName: "🧭 Run ESLint"
+              - task: NodeTool@0
+                inputs:
+                  versionSpec: "18.x"
+                  checkLatest: true
+                displayName: "Install Node.js"
 
-      - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@3
-        displayName: "🧭 Publish Guardian Artifacts - All Tools"
-        inputs:
-          ArtifactType: M365
-        condition: succeededOrFailed()
+              - script: npm install
+                displayName: Install dependencies
 
-      - task: AssetRetention@3
-        displayName: 🧭 Arrow Retention
-        inputs:
-          ArrowServiceConnection: "Arrow_uifabric_uifabric_PROD"
-          AssetGroupName: "$(System.TeamProject)_$(Build.DefinitionName)"
-          AssetNumber: "$(Build.BuildId)"
-          IsShipped: false
-          DropsToRetain: "CodeAnalysisLogs"
-        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
+              - script: |
+                  git config user.name "Fluent UI Build"
+                  git config user.email "fluentui-internal@service.microsoft.com"
+                  git remote set-url origin https://$(githubUser):$(githubPAT)@github.com/microsoft/use-disposable.git
+                displayName: Authenticate git for pushes
 
-      - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@2
-        displayName: "🧭 Guardian Break"
-        inputs:
-          GdnBreakPolicyMinSev: Warning
-          GdnBreakAllTools: true
-          GdnBreakGdnToolESLint: true
-          GdnBreakGdnToolESLintSeverity: Warning
-          GdnBreakPolicy: M365
-        condition: succeededOrFailed()
+              - script: |
+                  echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
+                displayName: Write .npmrc
 
-  - job: Release
-    dependsOn: Compliance
-    pool: "1ES-Host-Ubuntu"
-    workspace:
-      clean: all
-    steps:
-      # For multiline scripts, we want the whole task to fail if any line of the script fails.
-      # ADO doesn't have bash configured this way by default. To fix we override the SHELLOPTS built-in variable.
-      # https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
-      # The options below include ADO defaults (braceexpand:hashall:interactive-comments) plus
-      # errexit:errtrace for better error behavior.
-      - script: |
-          echo "##vso[task.setvariable variable=shellopts]braceexpand:hashall:interactive-comments:errexit:errtrace"
-        displayName: Force exit on error (bash)
+              - script: |
+                  npm run release -- $(publishVersion) --ci
+                displayName: Publish (official)
+                condition: eq(variables.prerelease, false)
+                env:
+                  NPM_TOKEN: $(npmToken)
 
-      - script: |
-          git checkout --track "origin/${BUILD_SOURCEBRANCH//refs\/heads\/}"
-          git pull
-        displayName: Re-attach HEAD
-
-      - task: NodeTool@0
-        inputs:
-          versionSpec: "16.x"
-          checkLatest: true
-        displayName: "Install Node.js"
-
-      - script: npm install
-        displayName: Install dependencies
-
-      - script: |
-          git config user.name "Fluent UI Build"
-          git config user.email "fluentui-internal@service.microsoft.com"
-          git remote set-url origin https://$(githubUser):$(githubPAT)@github.com/microsoft/use-disposable.git
-        displayName: Authenticate git for pushes
-
-      - script: |
-          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
-        displayName: Write .npmrc
-
-      - script: |
-          npm run release -- $(publishVersion) --ci
-        displayName: Publish (official)
-        condition: eq(variables.prerelease, false)
-        env:
-          NPM_TOKEN: $(npmToken)
-
-      - script: |
-          npm run release -- $(publishVersion) --preRelease $(prereleaseTag) --ci
-        displayName: Publish (prerelease)
-        condition: eq(variables.prerelease, true)
-        env:
-          NPM_TOKEN: $(npmToken)
+              - script: |
+                  npm run release -- $(publishVersion) --preRelease $(prereleaseTag) --ci
+                displayName: Publish (prerelease)
+                condition: eq(variables.prerelease, true)
+                env:
+                  NPM_TOKEN: $(npmToken)
